-- Inserts para DEPARTAMENTOS
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Guatemala');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('El Progreso');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Sacatepéquez');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Chimaltenango');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Escuintla');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Santa Rosa');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Sololá');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Totonicapán');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Quetzaltenango');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Suchitepéquez');

-- Inserts para MUNICIPIOS
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Ciudad de Guatemala');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Mixco');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Villa Nueva');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Antigua Guatemala');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Escuintla');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Quetzaltenango');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Chimaltenango');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Mazatenango');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Cobán');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Puerto Barrios');

-- Inserts para CODIGOS_POSTALES
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Zona 1, Ciudad de Guatemala');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Zona 10, Ciudad de Guatemala');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Zona 4 de Mixco');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Centro Antigua Guatemala');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Zona 1 Quetzaltenango');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Centro de Escuintla');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Zona 2 de Villa Nueva');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Centro de Chimaltenango');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Centro de Mazatenango');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Centro de Cobán');

-- Inserts para ROLES
INSERT INTO ROLES (ROL) VALUES ('Gerente General');
INSERT INTO ROLES (ROL) VALUES ('Gerente de Sucursal');
INSERT INTO ROLES (ROL) VALUES ('Cajero');
INSERT INTO ROLES (ROL) VALUES ('Ejecutivo de Cuenta');
INSERT INTO ROLES (ROL) VALUES ('Oficial de Préstamos');
INSERT INTO ROLES (ROL) VALUES ('Servicio al Cliente');
INSERT INTO ROLES (ROL) VALUES ('Analista de Riesgos');
INSERT INTO ROLES (ROL) VALUES ('Auditor Interno');
INSERT INTO ROLES (ROL) VALUES ('Supervisor de Operaciones');
INSERT INTO ROLES (ROL) VALUES ('Asistente Administrativo');

-- Inserts para TIPO_DE_SUCURSALES_AGENCIAS
INSERT INTO TIPO_DE_SUCURSALES_AGENCIAS (NOMBRE_TIPO) VALUES ('Sucursal Principal');
INSERT INTO TIPO_DE_SUCURSALES_AGENCIAS (NOMBRE_TIPO) VALUES ('Sucursal Regular');
INSERT INTO TIPO_DE_SUCURSALES_AGENCIAS (NOMBRE_TIPO) VALUES ('Agencia Express');
INSERT INTO TIPO_DE_SUCURSALES_AGENCIAS (NOMBRE_TIPO) VALUES ('Centro Financiero');
INSERT INTO TIPO_DE_SUCURSALES_AGENCIAS (NOMBRE_TIPO) VALUES ('Agencia Digital');
INSERT INTO TIPO_DE_SUCURSALES_AGENCIAS (NOMBRE_TIPO) VALUES ('Mini Agencia');
INSERT INTO TIPO_DE_SUCURSALES_AGENCIAS (NOMBRE_TIPO) VALUES ('Agencia Empresarial');
INSERT INTO TIPO_DE_SUCURSALES_AGENCIAS (NOMBRE_TIPO) VALUES ('Punto de Servicio');
INSERT INTO TIPO_DE_SUCURSALES_AGENCIAS (NOMBRE_TIPO) VALUES ('Agencia Virtual');
INSERT INTO TIPO_DE_SUCURSALES_AGENCIAS (NOMBRE_TIPO) VALUES ('Centro de Negocios');

-- Inserts para TIPO_DE_CUENTAS
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Cuenta de Ahorro');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Cuenta Corriente');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Cuenta Monetaria');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Cuenta de Ahorro Programado');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Cuenta Premium');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Cuenta Empresarial');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Cuenta Juvenil');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Cuenta de Nómina');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Cuenta de Inversión');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Cuenta Digital');

-- Inserts para ESTADOS_DE_TARJETAS
INSERT INTO ESTADOS_DE_TARJETAS (ESTADO) VALUES ('Activa');
INSERT INTO ESTADOS_DE_TARJETAS (ESTADO) VALUES ('Bloqueada');
INSERT INTO ESTADOS_DE_TARJETAS (ESTADO) VALUES ('Vencida');
INSERT INTO ESTADOS_DE_TARJETAS (ESTADO) VALUES ('En Mora');
INSERT INTO ESTADOS_DE_TARJETAS (ESTADO) VALUES ('Cancelada');
INSERT INTO ESTADOS_DE_TARJETAS (ESTADO) VALUES ('Robada/Perdida');
INSERT INTO ESTADOS_DE_TARJETAS (ESTADO) VALUES ('En Renovación');
INSERT INTO ESTADOS_DE_TARJETAS (ESTADO) VALUES ('Suspendida');
INSERT INTO ESTADOS_DE_TARJETAS (ESTADO) VALUES ('Por Activar');
INSERT INTO ESTADOS_DE_TARJETAS (ESTADO) VALUES ('En Disputa');

-- Inserts para ESTADOS_DE_PRESTAMOS
INSERT INTO ESTADOS_DE_PRESTAMOS (ESTADO) VALUES ('Al Día');
INSERT INTO ESTADOS_DE_PRESTAMOS (ESTADO) VALUES ('En Mora');
INSERT INTO ESTADOS_DE_PRESTAMOS (ESTADO) VALUES ('Cancelado');
INSERT INTO ESTADOS_DE_PRESTAMOS (ESTADO) VALUES ('Refinanciado');
INSERT INTO ESTADOS_DE_PRESTAMOS (ESTADO) VALUES ('En Proceso Legal');
INSERT INTO ESTADOS_DE_PRESTAMOS (ESTADO) VALUES ('Pre-aprobado');
INSERT INTO ESTADOS_DE_PRESTAMOS (ESTADO) VALUES ('Denegado');
INSERT INTO ESTADOS_DE_PRESTAMOS (ESTADO) VALUES ('En Revisión');
INSERT INTO ESTADOS_DE_PRESTAMOS (ESTADO) VALUES ('Congelado');
INSERT INTO ESTADOS_DE_PRESTAMOS (ESTADO) VALUES ('Liquidado');
INSERT INTO ESTADOS_DE_PRESTAMOS (ESTADO) VALUES ('Aprobado');


-- Inserts para TIPOS_DE_SUELDO
INSERT INTO TIPOS_DE_SUELDO (TIPO) VALUES ('Mensual');
INSERT INTO TIPOS_DE_SUELDO (TIPO) VALUES ('Quincenal');
INSERT INTO TIPOS_DE_SUELDO (TIPO) VALUES ('Semanal');
INSERT INTO TIPOS_DE_SUELDO (TIPO) VALUES ('Por Hora');
INSERT INTO TIPOS_DE_SUELDO (TIPO) VALUES ('Por Comisión');
INSERT INTO TIPOS_DE_SUELDO (TIPO) VALUES ('Base + Comisión');
INSERT INTO TIPOS_DE_SUELDO (TIPO) VALUES ('Por Proyecto');
INSERT INTO TIPOS_DE_SUELDO (TIPO) VALUES ('Anual');
INSERT INTO TIPOS_DE_SUELDO (TIPO) VALUES ('Bimensual');
INSERT INTO TIPOS_DE_SUELDO (TIPO) VALUES ('Variable');

-- Inserts para TIPOS_DE_TRANSACCIONES
INSERT INTO TIPOS_DE_TRANSACCIONES (TIPO) VALUES ('Depósito');
INSERT INTO TIPOS_DE_TRANSACCIONES (TIPO) VALUES ('Retiro');
INSERT INTO TIPOS_DE_TRANSACCIONES (TIPO) VALUES ('Transferencia');
INSERT INTO TIPOS_DE_TRANSACCIONES (TIPO) VALUES ('Pago de Servicios');
INSERT INTO TIPOS_DE_TRANSACCIONES (TIPO) VALUES ('Pago de Préstamo');
INSERT INTO TIPOS_DE_TRANSACCIONES (TIPO) VALUES ('Pago de Tarjeta');
INSERT INTO TIPOS_DE_TRANSACCIONES (TIPO) VALUES ('Cambio de Divisas');
INSERT INTO TIPOS_DE_TRANSACCIONES (TIPO) VALUES ('Compra con Tarjeta');
INSERT INTO TIPOS_DE_TRANSACCIONES (TIPO) VALUES ('Retiro ATM');
INSERT INTO TIPOS_DE_TRANSACCIONES (TIPO) VALUES ('Transferencia ACH');

-- Inserts para TIPOS_DE_ESTADOS_FINANCIEROS
INSERT INTO TIPOS_DE_ESTADOS_FINANCIEROS (TIPO, DESCRIPCION) VALUES ('Solvente', 'Estado financiero óptimo');
INSERT INTO TIPOS_DE_ESTADOS_FINANCIEROS (TIPO, DESCRIPCION) VALUES ('Equilibrio', 'Estado financiero estable');
INSERT INTO TIPOS_DE_ESTADOS_FINANCIEROS (TIPO, DESCRIPCION) VALUES ('Quiebra', 'Estado financiero crítico');

-- Inserts para UBICACIONES
INSERT INTO UBICACIONES (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_CODIGO_POSTAL) VALUES (1, 1, 1);
INSERT INTO UBICACIONES (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_CODIGO_POSTAL) VALUES (1, 2, 2);
INSERT INTO UBICACIONES (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_CODIGO_POSTAL) VALUES (1, 3, 3);
INSERT INTO UBICACIONES (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_CODIGO_POSTAL) VALUES (3, 4, 4);
INSERT INTO UBICACIONES (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_CODIGO_POSTAL) VALUES (9, 6, 5);
INSERT INTO UBICACIONES (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_CODIGO_POSTAL) VALUES (5, 5, 6);
INSERT INTO UBICACIONES (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_CODIGO_POSTAL) VALUES (1, 3, 7);
INSERT INTO UBICACIONES (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_CODIGO_POSTAL) VALUES (4, 7, 8);
INSERT INTO UBICACIONES (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_CODIGO_POSTAL) VALUES (10, 8, 9);
INSERT INTO UBICACIONES (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_CODIGO_POSTAL) VALUES (2, 9, 10);

-- Inserts para EMPLEADOS
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, ID_ROL, ID_DEPARTAMENTO, SUCURSAL, AGENCIA, TELEFONO) 
VALUES ('Juan', 'Pérez', 1, 1, 'Central', 'Principal', '5551234567');
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, ID_ROL, ID_DEPARTAMENTO, SUCURSAL, AGENCIA, TELEFONO) 
VALUES ('María', 'López', 2, 1, 'Zona 10', 'Express', '5552345678');
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, ID_ROL, ID_DEPARTAMENTO, SUCURSAL, AGENCIA, TELEFONO) 
VALUES ('Carlos', 'García', 3, 2, 'Mixco', 'Centro', '5553456789');
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, ID_ROL, ID_DEPARTAMENTO, SUCURSAL, AGENCIA, TELEFONO) 
VALUES ('Ana', 'Martínez', 4, 3, 'Antigua', 'Colonial', '5554567890');
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, ID_ROL, ID_DEPARTAMENTO, SUCURSAL, AGENCIA, TELEFONO) 
VALUES ('Pedro', 'Ramírez', 5, 4, 'Xela', 'Principal', '5555678901');
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, ID_ROL, ID_DEPARTAMENTO, SUCURSAL, AGENCIA, TELEFONO) 
VALUES ('Lucía', 'Hernández', 6, 5, 'Escuintla', 'Central', '5556789012');
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, ID_ROL, ID_DEPARTAMENTO, SUCURSAL, AGENCIA, TELEFONO) 
VALUES ('Roberto', 'Torres', 7, 1, 'Zona 1', 'Express', '5557890123');
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, ID_ROL, ID_DEPARTAMENTO, SUCURSAL, AGENCIA, TELEFONO) 
VALUES ('Sofia', 'Luna', 8, 2, 'Villa Nueva', 'Centro', '5558901234');
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, ID_ROL, ID_DEPARTAMENTO, SUCURSAL, AGENCIA, TELEFONO) 
VALUES ('Diego', 'Mendoza', 9, 3, 'Chimaltenango', 'Principal', '5559012345');
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, ID_ROL, ID_DEPARTAMENTO, SUCURSAL, AGENCIA, TELEFONO) 
VALUES ('Carmen', 'Sánchez', 10, 4, 'Mazatenango', 'Express', '5550123456');

-- Inserts para SUCURSALES_AGENCIAS
INSERT INTO SUCURSALES_AGENCIAS (NOMBRE, ID_TIPO, TELEFONO, ID_UBICACION, NUM_EMPLEADO, CAPACIDAD_ALAMCENAMIENTO) 
VALUES ('Sucursal Central', 1, '5551111111', 1, 50, 1000);
INSERT INTO SUCURSALES_AGENCIAS (NOMBRE, ID_TIPO, TELEFONO, ID_UBICACION, NUM_EMPLEADO, CAPACIDAD_ALAMCENAMIENTO) 
VALUES ('Agencia Zona 10', 2, '5552222222', 2, 30, 800);
INSERT INTO SUCURSALES_AGENCIAS (NOMBRE, ID_TIPO, TELEFONO, ID_UBICACION, NUM_EMPLEADO, CAPACIDAD_ALAMCENAMIENTO) 
VALUES ('Express Mixco', 3, '5553333333', 3, 15, 500);
INSERT INTO SUCURSALES_AGENCIAS (NOMBRE, ID_TIPO, TELEFONO, ID_UBICACION, NUM_EMPLEADO, CAPACIDAD_ALAMCENAMIENTO) 
VALUES ('Centro Antigua', 4, '5554444444', 4, 25, 700);

-- Inserts para CUENTAS
INSERT INTO CUENTAS (NUMERO_DE_CUENTA, ID_TIPO_DE_CUENTA, SALDO) VALUES ('1001-001-01', 1, 15000.00);
INSERT INTO CUENTAS (NUMERO_DE_CUENTA, ID_TIPO_DE_CUENTA, SALDO) VALUES ('1001-001-02', 2, 25000.00);
INSERT INTO CUENTAS (NUMERO_DE_CUENTA, ID_TIPO_DE_CUENTA, SALDO) VALUES ('1001-001-03', 3, 35000.00);
INSERT INTO CUENTAS (NUMERO_DE_CUENTA, ID_TIPO_DE_CUENTA, SALDO) VALUES ('1001-001-04', 4, 45000.00);
INSERT INTO CUENTAS (NUMERO_DE_CUENTA, ID_TIPO_DE_CUENTA, SALDO) VALUES ('1001-001-05', 5, 55000.00);
INSERT INTO CUENTAS (NUMERO_DE_CUENTA, ID_TIPO_DE_CUENTA, SALDO) VALUES ('1001-001-06', 6, 65000.00);
INSERT INTO CUENTAS (NUMERO_DE_CUENTA, ID_TIPO_DE_CUENTA, SALDO) VALUES ('1001-001-07', 7, 75000.00);
INSERT INTO CUENTAS (NUMERO_DE_CUENTA, ID_TIPO_DE_CUENTA, SALDO) VALUES ('1001-001-08', 8, 85000.00);
INSERT INTO CUENTAS (NUMERO_DE_CUENTA, ID_TIPO_DE_CUENTA, SALDO) VALUES ('1001-001-09', 9, 95000.00);
INSERT INTO CUENTAS (NUMERO_DE_CUENTA, ID_TIPO_DE_CUENTA, SALDO) VALUES ('1001-001-10', 10, 105000.00);

-- Inserts para CLIENTES
INSERT INTO CLIENTES (NOMBRE, APELLIDO, TELEFONO, ID_CUENTA) VALUES ('Luis', 'González', '5551234567', 1);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, TELEFONO, ID_CUENTA) VALUES ('Ana', 'Rodríguez', '5552345678', 2);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, TELEFONO, ID_CUENTA) VALUES ('Carlos', 'Pérez', '5553456789', 3);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, TELEFONO, ID_CUENTA) VALUES ('María', 'López', '5554567890', 4);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, TELEFONO, ID_CUENTA) VALUES ('José', 'Martínez', '5555678901', 5);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, TELEFONO, ID_CUENTA) VALUES ('Sandra', 'García', '5556789012', 6);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, TELEFONO, ID_CUENTA) VALUES ('Pedro', 'Hernández', '5557890123', 7);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, TELEFONO, ID_CUENTA) VALUES ('Laura', 'Sánchez', '5558901234', 8);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, TELEFONO, ID_CUENTA) VALUES ('Miguel', 'Torres', '5559012345', 9);
INSERT INTO CLIENTES (NOMBRE, APELLIDO, TELEFONO, ID_CUENTA) VALUES ('Carmen', 'Ramírez', '5550123456', 10);

-- Inserts para BOVEDAS
INSERT INTO BOVEDAS (ID_AGENCIA_SUCURSAL, FONDOS_DISPONIBLES) VALUES (1, 1000000.00);
INSERT INTO BOVEDAS (ID_AGENCIA_SUCURSAL, FONDOS_DISPONIBLES) VALUES (2, 750000.00);
INSERT INTO BOVEDAS (ID_AGENCIA_SUCURSAL, FONDOS_DISPONIBLES) VALUES (3, 500000.00);
INSERT INTO BOVEDAS (ID_AGENCIA_SUCURSAL, FONDOS_DISPONIBLES) VALUES (4, 850000.00);
INSERT INTO BOVEDAS (ID_AGENCIA_SUCURSAL, FONDOS_DISPONIBLES) VALUES (5, 650000.00);
INSERT INTO BOVEDAS (ID_AGENCIA_SUCURSAL, FONDOS_DISPONIBLES) VALUES (1, 950000.00);
INSERT INTO BOVEDAS (ID_AGENCIA_SUCURSAL, FONDOS_DISPONIBLES) VALUES (2, 550000.00);
INSERT INTO BOVEDAS (ID_AGENCIA_SUCURSAL, FONDOS_DISPONIBLES) VALUES (3, 450000.00);
INSERT INTO BOVEDAS (ID_AGENCIA_SUCURSAL, FONDOS_DISPONIBLES) VALUES (4, 800000.00);
INSERT INTO BOVEDAS (ID_AGENCIA_SUCURSAL, FONDOS_DISPONIBLES) VALUES (5, 700000.00);

-- Inserts para TARJETAS_DE_CREDITO
INSERT INTO TARJETAS_DE_CREDITO (ID_CLIENTE, NUMERO_DE_TARJETA, LIMITE_DE_CREDITO, SALDO_ACTUAL, FECHA_DE_EMISION, FECHA_DE_EXPIRACION, ID_ESTADO, FECHA_DE_CORTE, DÍA_DEL_CICLO) 
VALUES (1, '4532-7894-1234-5678', 25000.00, 5000.00, DATE '2023-01-01', DATE '2026-01-01', 1, DATE '2024-02-15', 15);
INSERT INTO TARJETAS_DE_CREDITO (ID_CLIENTE, NUMERO_DE_TARJETA, LIMITE_DE_CREDITO, SALDO_ACTUAL, FECHA_DE_EMISION, FECHA_DE_EXPIRACION, ID_ESTADO, FECHA_DE_CORTE, DÍA_DEL_CICLO) 
VALUES (2, '4532-7894-1234-5679', 35000.00, 15000.00, DATE '2023-02-01', DATE '2026-02-01', 1, DATE '2024-02-20', 20);
INSERT INTO TARJETAS_DE_CREDITO (ID_CLIENTE, NUMERO_DE_TARJETA, LIMITE_DE_CREDITO, SALDO_ACTUAL, FECHA_DE_EMISION, FECHA_DE_EXPIRACION, ID_ESTADO, FECHA_DE_CORTE, DÍA_DEL_CICLO) 
VALUES (3, '4532-7894-1234-5680', 45000.00, 20000.00, DATE '2023-03-01', DATE '2026-03-01', 2, DATE '2024-02-25', 25);
INSERT INTO TARJETAS_DE_CREDITO (ID_CLIENTE, NUMERO_DE_TARJETA, LIMITE_DE_CREDITO, SALDO_ACTUAL, FECHA_DE_EMISION, FECHA_DE_EXPIRACION, ID_ESTADO, FECHA_DE_CORTE, DÍA_DEL_CICLO) 
VALUES (4, '4532-7894-1234-5681', 55000.00, 25000.00, DATE '2023-04-01', DATE '2026-04-01', 1, DATE '2024-02-10', 10);
INSERT INTO TARJETAS_DE_CREDITO (ID_CLIENTE, NUMERO_DE_TARJETA, LIMITE_DE_CREDITO, SALDO_ACTUAL, FECHA_DE_EMISION, FECHA_DE_EXPIRACION, ID_ESTADO, FECHA_DE_CORTE, DÍA_DEL_CICLO) 
VALUES (5, '4532-7894-1234-5682', 65000.00, 30000.00, DATE '2023-05-01', DATE '2026-05-01', 1, DATE '2024-02-05', 5);
INSERT INTO TARJETAS_DE_CREDITO (ID_CLIENTE, NUMERO_DE_TARJETA, LIMITE_DE_CREDITO, SALDO_ACTUAL, FECHA_DE_EMISION, FECHA_DE_EXPIRACION, ID_ESTADO, FECHA_DE_CORTE, DÍA_DEL_CICLO) 
VALUES (6, '4532-7894-1234-5683', 75000.00, 35000.00, DATE '2023-06-01', DATE '2026-06-01', 1, DATE '2024-02-15', 15);
INSERT INTO TARJETAS_DE_CREDITO (ID_CLIENTE, NUMERO_DE_TARJETA, LIMITE_DE_CREDITO, SALDO_ACTUAL, FECHA_DE_EMISION, FECHA_DE_EXPIRACION, ID_ESTADO, FECHA_DE_CORTE, DÍA_DEL_CICLO) 
VALUES (7, '4532-7894-1234-5684', 85000.00, 40000.00, DATE '2023-07-01', DATE '2026-07-01', 3, DATE '2024-02-20', 20);
INSERT INTO TARJETAS_DE_CREDITO (ID_CLIENTE, NUMERO_DE_TARJETA, LIMITE_DE_CREDITO, SALDO_ACTUAL, FECHA_DE_EMISION, FECHA_DE_EXPIRACION, ID_ESTADO, FECHA_DE_CORTE, DÍA_DEL_CICLO) 
VALUES (8, '4532-7894-1234-5685', 95000.00, 45000.00, DATE '2023-08-01', DATE '2026-08-01', 1, DATE '2024-02-25', 25);
INSERT INTO TARJETAS_DE_CREDITO (ID_CLIENTE, NUMERO_DE_TARJETA, LIMITE_DE_CREDITO, SALDO_ACTUAL, FECHA_DE_EMISION, FECHA_DE_EXPIRACION, ID_ESTADO, FECHA_DE_CORTE, DÍA_DEL_CICLO) 
VALUES (9, '4532-7894-1234-5686', 100000.00, 50000.00, DATE '2023-09-01', DATE '2026-09-01', 1, DATE '2024-02-10', 10);
INSERT INTO TARJETAS_DE_CREDITO (ID_CLIENTE, NUMERO_DE_TARJETA, LIMITE_DE_CREDITO, SALDO_ACTUAL, FECHA_DE_EMISION, FECHA_DE_EXPIRACION, ID_ESTADO, FECHA_DE_CORTE, DÍA_DEL_CICLO) 
VALUES (10, '4532-7894-1234-5687', 150000.00, 75000.00, DATE '2023-10-01', DATE '2026-10-01', 1, DATE '2024-02-05', 5);

-- Inserts para PRESTAMOS
INSERT INTO PRESTAMOS (ID_CLIENTE, MONTO_DEL_PRESTAMO, TASA_DE_INTERES, FECHA_DE_DESEMBOLSO, FECHA_DE_VENCIMIENTO, SALDO_PENDIENTE, ID_ESTADO)
VALUES (1, 50000.00, 12.5, DATE '2023-01-15', DATE '2025-01-15', 45000.00, 1);
INSERT INTO PRESTAMOS (ID_CLIENTE, MONTO_DEL_PRESTAMO, TASA_DE_INTERES, FECHA_DE_DESEMBOLSO, FECHA_DE_VENCIMIENTO, SALDO_PENDIENTE, ID_ESTADO)
VALUES (2, 75000.00, 11.5, DATE '2023-02-15', DATE '2025-02-15', 70000.00, 1);
INSERT INTO PRESTAMOS (ID_CLIENTE, MONTO_DEL_PRESTAMO, TASA_DE_INTERES, FECHA_DE_DESEMBOLSO, FECHA_DE_VENCIMIENTO, SALDO_PENDIENTE, ID_ESTADO)
VALUES (3, 100000.00, 10.5, DATE '2023-03-15', DATE '2025-03-15', 95000.00, 2);
INSERT INTO PRESTAMOS (ID_CLIENTE, MONTO_DEL_PRESTAMO, TASA_DE_INTERES, FECHA_DE_DESEMBOLSO, FECHA_DE_VENCIMIENTO, SALDO_PENDIENTE, ID_ESTADO)
VALUES (4, 150000.00, 9.5, DATE '2023-04-15', DATE '2025-04-15', 140000.00, 1);
INSERT INTO PRESTAMOS (ID_CLIENTE, MONTO_DEL_PRESTAMO, TASA_DE_INTERES, FECHA_DE_DESEMBOLSO, FECHA_DE_VENCIMIENTO, SALDO_PENDIENTE, ID_ESTADO)
VALUES (5, 200000.00, 8.5, DATE '2023-05-15', DATE '2025-05-15', 190000.00, 1);
INSERT INTO PRESTAMOS (ID_CLIENTE, MONTO_DEL_PRESTAMO, TASA_DE_INTERES, FECHA_DE_DESEMBOLSO, FECHA_DE_VENCIMIENTO, SALDO_PENDIENTE, ID_ESTADO)
VALUES (6, 250000.00, 7.5, DATE '2023-06-15', DATE '2025-06-15', 240000.00, 1);
INSERT INTO PRESTAMOS (ID_CLIENTE, MONTO_DEL_PRESTAMO, TASA_DE_INTERES, FECHA_DE_DESEMBOLSO, FECHA_DE_VENCIMIENTO, SALDO_PENDIENTE, ID_ESTADO)
VALUES (7, 300000.00, 6.5, DATE '2023-07-15', DATE '2025-07-15', 290000.00, 3);
INSERT INTO PRESTAMOS (ID_CLIENTE, MONTO_DEL_PRESTAMO, TASA_DE_INTERES, FECHA_DE_DESEMBOLSO, FECHA_DE_VENCIMIENTO, SALDO_PENDIENTE, ID_ESTADO)
VALUES (8, 350000.00, 5.5, DATE '2023-08-15', DATE '2025-08-15', 340000.00, 1);
INSERT INTO PRESTAMOS (ID_CLIENTE, MONTO_DEL_PRESTAMO, TASA_DE_INTERES, FECHA_DE_DESEMBOLSO, FECHA_DE_VENCIMIENTO, SALDO_PENDIENTE, ID_ESTADO)
VALUES (9, 400000.00, 4.5, DATE '2023-09-15', DATE '2025-09-15', 390000.00, 1);
INSERT INTO PRESTAMOS (ID_CLIENTE, MONTO_DEL_PRESTAMO, TASA_DE_INTERES, FECHA_DE_DESEMBOLSO, FECHA_DE_VENCIMIENTO, SALDO_PENDIENTE, ID_ESTADO)
VALUES (10, 450000.00, 3.5, DATE '2023-10-15', DATE '2025-10-15', 440000.00, 1);

SELECT * FROM empleados;
