-- Insertar en DEPARTAMENTOS
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Finanzas');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Tecnología');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Recursos Humanos');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Atención al Cliente');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Legal');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Marketing');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Contabilidad');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Operaciones');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Ventas');
INSERT INTO DEPARTAMENTOS (DEPARTAMENTO) VALUES ('Auditoría');

-- Insertar en MUNICIPIOS
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Guatemala');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Antigua Guatemala');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Mixco');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Villa Nueva');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('San Miguel Petapa');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Fraijanes');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Amatitlán');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Santa Catarina Pinula');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Villa Canales');
INSERT INTO MUNICIPIOS (MUNICIPIO) VALUES ('Escuintla');

-- Insertar en CODIGOS_POSTALES
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Zona 1');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Zona 10');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Zona 12');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Zona 14');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Zona 18');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Zona 21');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Zona 7');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Zona 9');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Zona 11');
INSERT INTO CODIGOS_POSTALES (DIRECCION) VALUES ('Zona 15');

-- Insertar en ROLES
INSERT INTO ROLES (ROL) VALUES ('Cajero');
INSERT INTO ROLES (ROL) VALUES ('Gerente');
INSERT INTO ROLES (ROL) VALUES ('Asistente');
INSERT INTO ROLES (ROL) VALUES ('Analista');
INSERT INTO ROLES (ROL) VALUES ('Supervisor');
INSERT INTO ROLES (ROL) VALUES ('Contador');
INSERT INTO ROLES (ROL) VALUES ('Auditor');
INSERT INTO ROLES (ROL) VALUES ('Recepcionista');
INSERT INTO ROLES (ROL) VALUES ('Administrador');
INSERT INTO ROLES (ROL) VALUES ('Consultor');

-- Insertar en TIPO_DE_SUCURSALES_AGENCIAS
INSERT INTO TIPO_DE_SUCURSALES_AGENCIAS (NOMBRE_TIPO) VALUES ('Sucursal');
INSERT INTO TIPO_DE_SUCURSALES_AGENCIAS (NOMBRE_TIPO) VALUES ('Agencia');
INSERT INTO TIPO_DE_SUCURSALES_AGENCIAS (NOMBRE_TIPO) VALUES ('Centro de atención');
INSERT INTO TIPO_DE_SUCURSALES_AGENCIAS (NOMBRE_TIPO) VALUES ('Oficina móvil');
INSERT INTO TIPO_DE_SUCURSALES_AGENCIAS (NOMBRE_TIPO) VALUES ('Oficina principal');

-- Insertar en TIPO_DE_CUENTAS
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Cuenta Corriente');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Cuenta de Ahorros');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Depósito a Plazo');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Cuenta de Inversión');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Cuenta en Dólares');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Cuenta de Préstamos');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Cuenta de Negocios');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Fideicomiso');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Crédito Empresarial');
INSERT INTO TIPO_DE_CUENTAS (TIPO) VALUES ('Crédito Hipotecario');

-- Insertar en ESTADOS_DE_TARJETAS
INSERT INTO ESTADOS_DE_TARJETAS (ESTADO) VALUES ('Activa');
INSERT INTO ESTADOS_DE_TARJETAS (ESTADO) VALUES ('Inactiva');
INSERT INTO ESTADOS_DE_TARJETAS (ESTADO) VALUES ('Suspendida');
INSERT INTO ESTADOS_DE_TARJETAS (ESTADO) VALUES ('Bloqueada');
INSERT INTO ESTADOS_DE_TARJETAS (ESTADO) VALUES ('Pendiente de activación');

-- Insertar en ESTADOS_DE_PRESTAMOS
INSERT INTO ESTADOS_DE_PRESTAMOS (ESTADO) VALUES ('Activo');
INSERT INTO ESTADOS_DE_PRESTAMOS (ESTADO) VALUES ('Pendiente');
INSERT INTO ESTADOS_DE_PRESTAMOS (ESTADO) VALUES ('Cancelado');
INSERT INTO ESTADOS_DE_PRESTAMOS (ESTADO) VALUES ('Mora');
INSERT INTO ESTADOS_DE_PRESTAMOS (ESTADO) VALUES ('Finalizado');

-- Insertar en TIPOS_DE_SUELDO
INSERT INTO TIPOS_DE_SUELDO (TIPO) VALUES ('Mensual');
INSERT INTO TIPOS_DE_SUELDO (TIPO) VALUES ('Quincenal');
INSERT INTO TIPOS_DE_SUELDO (TIPO) VALUES ('Semanal');
INSERT INTO TIPOS_DE_SUELDO (TIPO) VALUES ('Diario');
INSERT INTO TIPOS_DE_SUELDO (TIPO) VALUES ('Honorarios');

-- Insertar en TIPOS_DE_TRANSACCIONES
INSERT INTO TIPOS_DE_TRANSACCIONES (TIPO) VALUES ('Depósito');
INSERT INTO TIPOS_DE_TRANSACCIONES (TIPO) VALUES ('Retiro');
INSERT INTO TIPOS_DE_TRANSACCIONES (TIPO) VALUES ('Transferencia');
INSERT INTO TIPOS_DE_TRANSACCIONES (TIPO) VALUES ('Pago de préstamo');
INSERT INTO TIPOS_DE_TRANSACCIONES (TIPO) VALUES ('Pago de tarjeta');

-- Insertar en TIPOS_DE_ESTADOS_FINANCIEROS
INSERT INTO TIPOS_DE_ESTADOS_FINANCIEROS (TIPO, DESCRIPCION) VALUES ('Solvente', 'El banco tiene buena salud financiera');
INSERT INTO TIPOS_DE_ESTADOS_FINANCIEROS (TIPO, DESCRIPCION) VALUES ('Equilibrio', 'El banco está en equilibrio');
INSERT INTO TIPOS_DE_ESTADOS_FINANCIEROS (TIPO, DESCRIPCION) VALUES ('Quiebra', 'El banco tiene pérdidas significativas');

-- Insertar en UBICACIONES (requiere ID de DEPARTAMENTOS, MUNICIPIOS y CODIGOS_POSTALES)
INSERT INTO UBICACIONES (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_CODIGO_POSTAL) VALUES (1, 1, 1);
INSERT INTO UBICACIONES (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_CODIGO_POSTAL) VALUES (2, 2, 2);
INSERT INTO UBICACIONES (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_CODIGO_POSTAL) VALUES (3, 3, 3);
INSERT INTO UBICACIONES (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_CODIGO_POSTAL) VALUES (4, 4, 4);
INSERT INTO UBICACIONES (ID_DEPARTAMENTO, ID_MUNICIPIO, ID_CODIGO_POSTAL) VALUES (5, 5, 5);

-- Insertar en EMPLEADOS (requiere ID_ROL y ID_DEPARTAMENTO)
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, ID_ROL, ID_DEPARTAMENTO, SUCURSAL, AGENCIA, TELEFONO) VALUES ('Juan', 'Perez', 1, 1, 'Sucursal Central', 'Agencia 1', '555-1234');
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, ID_ROL, ID_DEPARTAMENTO, SUCURSAL, AGENCIA, TELEFONO) VALUES ('Maria', 'Lopez', 2, 2, 'Sucursal Norte', 'Agencia 2', '555-5678');
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, ID_ROL, ID_DEPARTAMENTO, SUCURSAL, AGENCIA, TELEFONO) VALUES ('Carlos', 'Martinez', 3, 3, 'Sucursal Sur', 'Agencia 3', '555-9012');
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, ID_ROL, ID_DEPARTAMENTO, SUCURSAL, AGENCIA, TELEFONO) VALUES ('Ana', 'Rodriguez', 4, 4, 'Sucursal Este', 'Agencia 4', '555-3456');
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, ID_ROL, ID_DEPARTAMENTO, SUCURSAL, AGENCIA, TELEFONO) VALUES ('Luis', 'Gomez', 5, 5, 'Sucursal Oeste', 'Agencia 5', '555-7890');

-- Insertar en CLIENTES
INSERT INTO CLIENTES (NOMBRE, APELLIDO, TELEFONO, CORREO, DIRECCION, ESTADO) VALUES ('Jose', 'Ramirez', '555-1212', 'jose@gmail.com', 'Guatemala', 'ACTIVO');
INSERT INTO CLIENTES (NOMBRE, APELLIDO, TELEFONO, CORREO, DIRECCION, ESTADO) VALUES ('Sofia', 'Garcia', '555-1313', 'sofia@gmail.com', 'Antigua', 'INACTIVO');

-- Insertar en CUENTAS (requiere ID_CLIENTE)
INSERT INTO CUENTAS (ID_CLIENTE, NUMERO_CUENTA, ID_TIPO_CUENTA, ESTADO) VALUES (1, '9876543', 1, 'ACTIVA');
INSERT INTO CUENTAS (ID_CLIENTE, NUMERO_CUENTA, ID_TIPO_CUENTA, ESTADO) VALUES (2, '1234567', 2, 'ACTIVA');

-- Insertar en PRESTAMOS
INSERT INTO PRESTAMOS (NUMERO_CUENTA, MONTO, ESTADO, NUMERO_CUENTA_COBRO) VALUES (1, 5000, 'Pendiente', '9876543');
INSERT INTO PRESTAMOS (NUMERO_CUENTA, MONTO, ESTADO, NUMERO_CUENTA_COBRO) VALUES (2, 10000, 'Pendiente', '1234567');